export const images = {
    'Mattar Paneer': '/matterPanner.jpeg',
    'Saag Paneer': '/saagPanner.jpeg',
    'Chilli Paneer': '/p.jpg',
    'Paneer Tikka': '/paneerTikka.jpeg',
    'Vegetable Biryani': '/vb.jpg',
    'Paneer Biryani': '/paneerBiryani.jpg',
    'Mushroom Biryani': '/mb.jpg',
    'Jeera Rice': '/jr.jpg',
    'Veg Fried Rice': '/vegFriedRIce.webp',
    'Andhra Pulao': '/ap.jpg',
    'Vegetable Spring Rolls': '/vsgs.jpg', 
    'Stuffed Mushrooms': '/mushroomRecipe.jpeg',
    'Hara Bhara Kabab': '/haraBaraKabab.jpg',
    'Paneer Butter Masala': '/pbm.jpg',
    'Aloo Gobi': '/alooGobi.jpg',
    'Chana Masala': '/chanaMasala.jpg',
    'Gobi Manchurian': '/vm.jpg',
    'Baby Corn Chilly': '/babyCornChilli.jpeg',
    'Palak Paneer':'/palak.jpeg',
    'Paneer 65':'/p5.jpg',
    'Mixed Veg Curry': '/vegMixCurry.jpg',
    'Methi Chaman': '/methiChaman.jpeg',
    'Chicken Wings Biryani':'/cwb.jpeg',
    'Mutton Dum biriyani':'/mbs.jpg',
    'Mutton Curry':'/mc.jpg',
    'Mutton Haleem':'/mh.jpg',
    'Mutton Ghee Roast':'/msd.jpg',
    'Mutton Manchurian':'/mman.jpg',
    'Punjabi Mutton Curry':'/pmc.jpg',
    'Mughlai Karahi Gosht':'/mmc.jpg',
    'Pepper Mutton':'/pm.jpg',
    'Mutton Chaap':'/mcha.jpg',
    'Kashmiri Rogan Josh':'/krj.jpg',
    'Shahi Mutton Curry':'/smc.jpg',
    'Chicken Shangrilla':'/csh.jpg',
    'Kadai Chicken':'/kc.jpg',
    'Dragon Chicken':'/dc.jpg',
    'Andhra Chicken Curry (Boneless)':'/acc.jpg',
    'Chicken Tikka':'/cts.jpg',
    'Chicken Wings':'/cws.jpg',
    'Butter Chicken (Murgh Makhani)':'/bc.jpg',
    'Fish Curry':'/fc.jpg',
    'Fish Tacos':'/ft.jpg',
    'Garlic Butter Prawns':'/gbp.jpg',
    'Crab Curry':'/cc.jpg',
    'Crab Fry':'/cfs.jpg',
    'Prawns Butter Masala':'/pbms.jpg',
    'Prawns 65':'/p65.jpg',
    'Rajugari Chepala Pulusu':'/rcps.jpg',
    'Fish Fry':'/ffs.jpg',
    'Chicken Wings Biryani':'/cwbir.jpg',
    'Gongura Chicken Biryani':'/gcbs.jpg',
    'Mutton Fry Piece Biryani':'/mfp2.jpg',
    'Prawn Biryani':'/pbs.jpg',
    'Mutton Biryani':'/mbir.jpg',
    'Dhumm Chicken Biryani':'/dcbs.jpg',
    'Mutton Dum biryani':'/dmb.jpg',  
  };