export const nonVegBiryaniRecipes = [  
    {
        "title": "Chicken Wings Biryani",
        "ingredients": [
          "500g chicken wings",
          "2 cups basmati rice",
          "2 onions, thinly sliced",
          "2 tomatoes, chopped",
          "1/2 cup yogurt",
          "1 tbsp ginger-garlic paste",
          "2-3 green chilies, slit",
          "1 tsp red chili powder",
          "1/2 tsp turmeric powder",
          "1 tsp garam masala",
          "1 tbsp biryani masala",
          "1/4 cup fresh coriander, chopped",
          "1/4 cup fresh mint leaves, chopped",
          "1 tbsp lemon juice",
          "4 tbsp ghee or oil",
          "1-2 each whole spices (bay leaf, cloves, cardamom, cinnamon)",
          "Salt to taste",
          "4 cups water"
        ],
        "instructions": [
          "Rinse and soak the basmati rice in water for 30 minutes. Drain.",
          "Heat ghee or oil in a large pot. Add whole spices and sauté until fragrant.",
          "Add thinly sliced onions and sauté until golden brown.",
          "Add ginger-garlic paste and green chilies, sauté for a minute.",
          "Add chopped tomatoes, turmeric powder, red chili powder, and salt. Cook until tomatoes turn soft.",
          "Add chicken wings and mix well. Cook until the chicken changes color.",
          "Add yogurt, garam masala, biryani masala, fresh coriander, mint leaves, and lemon juice. Cook for another 5-7 minutes.",
          "In a separate pot, bring 4 cups of water to a boil. Add soaked and drained rice, and cook until the rice is 70% cooked. Drain and set aside.",
          "Layer the partially cooked rice over the chicken wings mixture. Sprinkle some fried onions, fresh coriander, and mint leaves on top.",
          "Cover the pot with a tight-fitting lid and cook on low heat for 20-25 minutes until the rice is fully cooked and the flavors are well blended.",
          "Serve hot with raita or a side salad."
        ],
        "time": "Prep time: 30 minutes, Cook time: 35-40 minutes"
      },
      {
        "title": "Gongura Chicken Biryani",
        "ingredients": [
          "500g chicken, cut into pieces",
          "2 cups basmati rice",
          "1 cup gongura (sorrel) leaves, finely chopped",
          "2 onions, thinly sliced",
          "2 tomatoes, chopped",
          "1/2 cup yogurt",
          "1 tbsp ginger-garlic paste",
          "2-3 green chilies, slit",
          "1 tsp red chili powder",
          "1/2 tsp turmeric powder",
          "1 tsp garam masala",
          "1 tbsp biryani masala",
          "1/4 cup fresh coriander, chopped",
          "1/4 cup fresh mint leaves, chopped",
          "1 tbsp lemon juice",
          "4 tbsp ghee or oil",
          "1-2 each whole spices (bay leaf, cloves, cardamom, cinnamon)",
          "Salt to taste",
          "4 cups water"
        ],
        "instructions": [
          "Rinse and soak the basmati rice in water for 30 minutes. Drain.",
          "Heat ghee or oil in a large pot. Add whole spices and sauté until fragrant.",
          "Add thinly sliced onions and sauté until golden brown.",
          "Add ginger-garlic paste and green chilies, sauté for a minute.",
          "Add chopped tomatoes, turmeric powder, red chili powder, and salt. Cook until tomatoes turn soft.",
          "Add chicken pieces and mix well. Cook until the chicken changes color.",
          "Add yogurt, garam masala, biryani masala, fresh coriander, mint leaves, and lemon juice. Cook for another 5-7 minutes.",
          "Add finely chopped gongura leaves and cook until they wilt and blend well with the chicken.",
          "In a separate pot, bring 4 cups of water to a boil. Add soaked and drained rice, and cook until the rice is 70% cooked. Drain and set aside.",
          "Layer the partially cooked rice over the chicken and gongura mixture. Sprinkle some fried onions, fresh coriander, and mint leaves on top.",
          "Cover the pot with a tight-fitting lid and cook on low heat for 20-25 minutes until the rice is fully cooked and the flavors are well blended.",
          "Serve hot with raita or a side salad."
        ],
        "time": "Prep time: 30 minutes, Cook time: 35-40 minutes"
      },
      {
        "title": "Mutton Fry Piece Biryani",
        "ingredients": [
          "500g mutton, boneless, cut into pieces",
          "2 cups basmati rice",
          "2 onions, thinly sliced",
          "2 tomatoes, chopped",
          "1/2 cup yogurt",
          "1 tbsp ginger-garlic paste",
          "2-3 green chilies, slit",
          "1 tsp red chili powder",
          "1/2 tsp turmeric powder",
          "1 tsp garam masala",
          "1 tbsp biryani masala",
          "1/4 cup fresh coriander, chopped",
          "1/4 cup fresh mint leaves, chopped",
          "1 tbsp lemon juice",
          "4 tbsp ghee or oil",
          "1-2 each whole spices (bay leaf, cloves, cardamom, cinnamon)",
          "Salt to taste",
          "4 cups water"
        ],
        "instructions": [
          "Rinse and soak the basmati rice in water for 30 minutes. Drain.",
          "Heat ghee or oil in a large pot. Add whole spices and sauté until fragrant.",
          "Add thinly sliced onions and sauté until golden brown.",
          "Add ginger-garlic paste and green chilies, sauté for a minute.",
          "Add chopped tomatoes, turmeric powder, red chili powder, and salt. Cook until tomatoes turn soft.",
          "Add mutton pieces and cook until they are browned and cooked through.",
          "Add yogurt, garam masala, biryani masala, fresh coriander, mint leaves, and lemon juice. Cook for another 5-7 minutes.",
          "In a separate pot, bring 4 cups of water to a boil. Add soaked and drained rice, and cook until the rice is 70% cooked. Drain and set aside.",
          "Layer the partially cooked rice over the mutton fry mixture. Sprinkle some fried onions, fresh coriander, and mint leaves on top.",
          "Cover the pot with a tight-fitting lid and cook on low heat for 20-25 minutes until the rice is fully cooked and the flavors are well blended.",
          "Serve hot with raita or a side salad."
        ],
        "time": "Prep time: 30 minutes, Cook time: 35-40 minutes"
      },
      {
        title: 'Prawn Biryani',
        ingredients: [
          '500g prawns, peeled and deveined',
          '1/2 cup yogurt',
          '2 tbsp ginger-garlic paste',
          '1 tsp red chili powder',
          '1 tsp turmeric powder',
          '1 tsp garam masala',
          'Salt to taste',
          '2 cups basmati rice',
          '2 large onions, thinly sliced',
          '2 tomatoes, chopped',
          '2 green chilies, slit',
          '1/2 cup fresh coriander leaves, chopped',
          '1/2 cup fresh mint leaves, chopped',
          '1 tsp cumin seeds',
          '1 tsp biryani masala',
          '1/2 cup milk',
          'A pinch of saffron strands',
          '4 tbsp ghee or vegetable oil',
          'Fried onions for garnish'
        ],
        instructions: [
          'Marinate Prawns:',
          'Mix yogurt, ginger-garlic paste, red chili powder, turmeric, garam masala, and salt. Marinate prawns for 30 minutes.',
          '',
          'Cook Rice:',
          'Boil 2 cups of water with bay leaves, cardamom, cloves, cinnamon, and salt. Add rice and cook until 70-80% done. Drain and set aside.',
          '',
          'Cook Prawns:',
          'Heat ghee/oil, add cumin seeds, onions, and sauté until golden. Add ginger-garlic paste, green chilies, tomatoes, and cook until soft. Add marinated prawns, biryani masala, and cook until prawns are done.',
          '',
          'Layer Biryani:',
          'Layer cooked prawns and rice in a pot. Sprinkle coriander, mint, and fried onions. Repeat layers. Add saffron milk.',
          '',
          'Dum Cooking:',
          'Cover tightly and cook on low heat for 20-25 minutes. Let rest for 10 minutes.',
          '',
          'Serve:',
          'Fluff and serve hot with raita or salad.'
        ],
        time: "Prep time: 30 minutes, Cook time: 35-40 minutes"
      },
      {
        title: 'Mutton Biryani',
        ingredients: [
          '500g mutton, cut into pieces',
          '1 cup yogurt',
          '2 tbsp ginger-garlic paste',
          '1 tsp red chili powder',
          '1 tsp turmeric powder',
          '1 tsp garam masala',
          'Salt to taste',
          '2 cups basmati rice',
          '2 large onions, thinly sliced',
          '2 tomatoes, chopped',
          '2 green chilies, slit',
          '1/2 cup fresh coriander leaves, chopped',
          '1/2 cup fresh mint leaves, chopped',
          '1 tsp cumin seeds',
          '1 tsp biryani masala',
          '1/2 cup milk',
          'A pinch of saffron strands',
          '4 tbsp ghee or vegetable oil',
          'Fried onions for garnish'
        ],
        instructions: [
          'Marinate Mutton:',
          'Mix yogurt, ginger-garlic paste, red chili powder, turmeric, garam masala, and salt. Marinate mutton for 2 hours.',
          '',
          'Cook Rice:',
          'Boil 2 cups of water with bay leaves, cardamom, cloves, cinnamon, and salt. Add rice and cook until 70-80% done. Drain and set aside.',
          '',
          'Cook Mutton:',
          'Heat ghee/oil, add cumin seeds, onions, and sauté until golden. Add ginger-garlic paste, green chilies, tomatoes, and cook until soft. Add marinated mutton, biryani masala, and cook until mutton is browned. Pressure cook with water until tender.',
          '',
          'Layer Biryani:',
          'Layer cooked mutton and rice in a pot. Sprinkle coriander, mint, and fried onions. Repeat layers. Add saffron milk.',
          '',
          'Dum Cooking:',
          'Cover tightly and cook on low heat for 20-25 minutes. Let rest for 10 minutes.',
          '',
          'Serve:',
          'Fluff and serve hot with raita or salad.'
        ],
        time:'1 hour 30 mintues'
      },
      {
        "title": "Dhumm Chicken Biryani",
        "ingredients": [
          "500g chicken, cut into pieces",
          "2 cups basmati rice, soaked for 30 minutes and drained",
          "2 onions, thinly sliced",
          "2 tomatoes, finely chopped",
          "1/2 cup yogurt",
          "1/4 cup ghee or vegetable oil",
          "2 tbsp ginger-garlic paste",
          "2 green chilies, slit",
          "1/2 tsp saffron strands, soaked in 2 tbsp warm milk",
          "1/4 cup chopped mint leaves",
          "1/4 cup chopped cilantro (coriander) leaves",
          "2 bay leaves",
          "4-5 green cardamom pods",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1 tsp cumin seeds",
          "1 tsp garam masala powder",
          "1 tsp biryani masala powder",
          "1/2 tsp turmeric powder",
          "1/2 tsp red chili powder (adjust to taste)",
          "Salt to taste",
          "Water as needed"
        ],
        "instructions": [
          "Marinate the Chicken:",
          "In a bowl, mix chicken pieces with yogurt, ginger-garlic paste, turmeric powder, red chili powder, garam masala powder, biryani masala powder, half of the chopped mint leaves, half of the chopped cilantro leaves, and salt. Let it marinate for at least 2 hours or overnight in the refrigerator.",
          "Cook the Rice:",
          "Bring a large pot of water to a boil. Add salt and bay leaves. Add soaked and drained rice and cook until it is 70% cooked. Drain and set aside.",
          "Prepare the Dhumm Chicken Biryani:",
          "Heat ghee or oil in a heavy-bottomed pot over medium heat.",
          "Add cumin seeds, bay leaves, green cardamom pods, cinnamon stick, and cloves. Saute until fragrant.",
          "Add sliced onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften.",
          "Add marinated chicken to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally.",
          "Layer the partially cooked rice over the chicken mixture. Sprinkle with remaining mint leaves and cilantro leaves.",
          "Drizzle saffron milk over the rice. Cover the pot with a tight-fitting lid.",
          "Reduce heat to low and cook for 20-25 minutes, or until the rice and chicken are fully cooked and tender.",
          "Once done, gently fluff the biryani with a fork.",
          "Serve hot with raita and salad.",
          "Enjoy your flavorful Dhumm Chicken Biryani!"
        ],
        "time": "Prep time: 30 minutes, Cook time: 1 hour (may vary)"
      },
      {
        "title": "Mutton Dum biryani",
        "ingredients": [
          "500g chicken or mutton, cut into pieces",
          "2 cups basmati rice, soaked for 30 minutes and drained",
          "2 onions, thinly sliced",
          "2 tomatoes, finely chopped",
          "1/2 cup yogurt",
          "1/4 cup ghee or vegetable oil",
          "2 tbsp ginger-garlic paste",
          "2 green chilies, slit",
          "1/2 tsp saffron strands, soaked in 2 tbsp warm milk",
          "1/4 cup chopped mint leaves",
          "1/4 cup chopped cilantro (coriander) leaves",
          "2 bay leaves",
          "4-5 green cardamom pods",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1 tsp cumin seeds",
          "1 tsp garam masala powder",
          "1 tsp biryani masala powder",
          "1/2 tsp turmeric powder",
          "1/2 tsp red chili powder (adjust to taste)",
          "Salt to taste",
          "Water as needed"
        ],
        "instructions": [
          "Marinate the Meat:",
          "In a bowl, mix chicken or mutton pieces with yogurt, ginger-garlic paste, turmeric powder, red chili powder, garam masala powder, biryani masala powder, half of the chopped mint leaves, half of the chopped cilantro leaves, and salt. Let it marinate for at least 2 hours or overnight in the refrigerator.",
          "Cook the Rice:",
          "Bring a large pot of water to a boil. Add salt and bay leaves. Add soaked and drained rice and cook until it is 70% cooked. Drain and set aside.",
          "Prepare the Dhumbiriyani:",
          "Heat ghee or oil in a heavy-bottomed pot over medium heat.",
          "Add cumin seeds, bay leaves, green cardamom pods, cinnamon stick, and cloves. Saute until fragrant.",
          "Add sliced onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften.",
          "Add marinated meat to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally.",
          "Layer the partially cooked rice over the meat mixture. Sprinkle with remaining mint leaves and cilantro leaves.",
          "Drizzle saffron milk over the rice. Cover the pot with a tight-fitting lid.",
          "Reduce heat to low and cook for 20-25 minutes, or until the rice and meat are fully cooked and tender.",
          "Once done, gently fluff the biryani with a fork.",
          "Serve hot with raita and salad.",
          "Enjoy your flavorful Dhumbiriyani!"
        ],
        "time": "Prep time: 30 minutes, Cook time: 1 hour (may vary)"
      }
];
