export const paneerRecipes =  [
      {
        title: 'Mattar Paneer',
        ingredients: [
          '1 cup green peas (matar)',
          '1 cup paneer (Indian cottage cheese), cubed',
          '1 medium onion, finely chopped',
          '2 cloves garlic, minced',
          '1-inch ginger, grated',
          '1 tsp garam masala',
          '1/2 tsp red chili powder',
          '1/4 tsp turmeric powder',
          '1/4 cup chopped fresh cilantro',
          'Salt to taste',
          'Oil or butter for cooking',
        ],
        instructions: [
          'Heat oil or butter in a pan over medium heat.',
          'Add onion and cook until translucent.',
          'Add garlic and ginger and cook for 1 minute.',
          'Add peas, paneer, garam masala, red chili powder, turmeric powder, and salt.',
          'Cook for 5-7 minutes, stirring occasionally, until peas are tender.',
          'Garnish with chopped cilantro and serve hot with rice or roti.',
        ],
        time: '30 minutes',
      },
      {
        title: 'Saag Paneer',
        ingredients: [
          '1 bunch spinach, washed and chopped',
          '1 cup paneer (Indian cottage cheese), cubed',
          '1 medium onion, finely chopped',
          '2 cloves garlic, minced',
          '1-inch ginger, grated',
          '1/2 tsp cumin powder',
          '1/4 tsp coriander powder',
          '1/4 tsp red chili powder',
          '1/4 tsp turmeric powder',
          '1/4 cup chopped fresh cilantro',
          'Salt to taste',
          'Oil or butter for cooking',
        ],
        instructions: [
          'Heat oil or butter in a pan over medium heat.',
          'Add onion and cook until translucent.',
          'Add garlic and ginger and cook for 1 minute.',
          'Add spinach, cumin powder, coriander powder, red chili powder, turmeric powder, and salt.',
          'Cook for 5-7 minutes, stirring occasionally, until spinach is wilted.',
          'Add paneer and cook for 2-3 minutes, until heated through.',
          'Garnish with chopped cilantro and serve hot with rice or roti.',
        ],
        time: '35 minutes',
      },
      {
        title: 'Chilli Paneer',
        ingredients: [
          '1 cup paneer (Indian cottage cheese), cubed',
          '1 medium onion, finely chopped',
          '2 cloves garlic, minced',
          '1-inch ginger, grated',
          '1/2 tsp red chili powder',
          '1/4 tsp black pepper powder',
          '1/4 tsp turmeric powder',
          '1/4 cup soy sauce',
          '1 tbsp vinegar',
          '1 tbsp sugar',
          '1 tbsp cornstarch',
          'Oil for frying',
          'Salt to taste',
        ],
        instructions: [
          'Mix together soy sauce, vinegar, sugar, cornstarch, and salt in a bowl.',
          'Heat oil in a pan over medium heat and fry paneer cubes until golden brown.',
          'Remove paneer from pan and set aside.',
          'Add onion, garlic, and ginger to the pan and cook until fragrant.',
          'Add red chili powder, black pepper powder, and turmeric powder.',
          'Add the soy sauce mixture and cook for 2-3 minutes, until sauce thickens.',
          'Return paneer to the pan and coat with the sauce.',
          'Serve hot with rice or noodles.',
        ],
        time: '40 minutes',
      },
      {
        title: 'Palak Paneer',
        ingredients: [
          'Fresh spinach (palak): 250g',
          'Paneer (cottage cheese), cubed: 200g',
          'Onion, finely chopped: 1',
          'Tomato, finely chopped: 2',
          'Green chilies: 2',
          'Ginger-garlic paste: 1 tsp',
          'Cumin seeds: 1 tsp',
          'Garam masala: 1/2 tsp',
          'Red chili powder: 1/2 tsp',
          'Turmeric powder: 1/4 tsp',
          'Fresh cream: 2 tbsp (optional)',
          'Salt: to taste',
          'Oil: 2 tbsp',
        ],
        instructions: [
          'Blanch spinach in boiling water for 2 minutes, then immediately transfer to ice-cold water. Drain and blend to a smooth paste with green chilies.',
          'Heat oil in a pan, add cumin seeds and let them splutter. Add finely chopped onions and sauté until golden brown.',
          'Add ginger-garlic paste and sauté for a minute.',
          'Add chopped tomatoes, turmeric powder, red chili powder, and salt. Cook until tomatoes turn soft and oil starts to separate.',
          'Add the spinach puree and mix well. Cook for 5-7 minutes on low flame.',
          'Add paneer cubes and garam masala. Stir gently and cook for another 3-4 minutes.',
          'Add fresh cream (optional) and mix well.',
          'Serve hot with naan or rice.',
        ],
        time: '30 minutes',
      },
      {
        title: 'Paneer Tikka',
        ingredients: [
          'Paneer (cottage cheese), cubed: 250g',
          'Thick yogurt: 1 cup',
          'Ginger-garlic paste: 1 tbsp',
          'Red chili powder: 1 tsp',
          'Turmeric powder: 1/2 tsp',
          'Garam masala: 1 tsp',
          'Coriander powder: 1 tsp',
          'Cumin powder: 1/2 tsp',
          'Chaat masala: 1 tsp',
          'Lemon juice: 1 tbsp',
          'Salt: to taste',
          'Oil: 2 tbsp',
          'Skewers: as needed'
        ],
        instructions: [
          'In a bowl, mix yogurt, ginger-garlic paste, red chili powder, turmeric powder, garam masala, coriander powder, cumin powder, chaat masala, lemon juice, salt, and oil to make a marinade.',
          'Add paneer cubes to the marinade and coat them well. Let it marinate for at least 1 hour.',
          'Preheat the oven to 200°C (392°F).',
          'Thread the marinated paneer onto skewers.',
          'Bake in the preheated oven for 15-20 minutes or until the paneer is golden brown, turning once halfway through.',
          'Serve hot with mint chutney and lemon wedges.'
        ],
        time: '30 minutes (plus marination time)'
      },
      
      {
        title: 'Paneer 65',
        ingredients: [
          'Paneer (cottage cheese), cubed: 250g',
          'Cornflour: 1/2 cup',
          'All-purpose flour: 1/4 cup',
          'Ginger-garlic paste: 1 tsp',
          'Red chili powder: 1 tsp',
          'Salt: to taste',
          'Water: as needed',
          'Oil: for frying',
          'Oil: 2 tbsp',
          'Ginger, finely chopped: 1 tbsp',
          'Garlic, finely chopped: 1 tbsp',
          'Green chilies, slit: 2',
          'Curry leaves: a few',
          'Red chili sauce: 2 tbsp',
          'Tomato ketchup: 2 tbsp',
          'Soy sauce: 1 tbsp',
          'Vinegar: 1 tsp',
          'Cornflour slurry: 1 tbsp cornflour mixed in 1/4 cup water',
          'Fresh coriander, chopped: for garnish'
        ],
        instructions: [
          'Mix cornflour, all-purpose flour, ginger-garlic paste, red chili powder, salt, and water to make a thick batter.',
          'Dip paneer cubes in the batter and deep fry until golden brown. Set aside.',
          'In a pan, heat oil and sauté ginger, garlic, green chilies, and curry leaves.',
          'Add red chili sauce, tomato ketchup, soy sauce, and vinegar. Mix well.',
          'Add cornflour slurry to the mixture and cook until the sauce thickens.',
          'Add fried paneer and toss to coat with the sauce.',
          'Garnish with chopped fresh coriander and serve hot.'
        ],
        time: '50 minutes' 
      
      },
      

    ];

      