export const biryanis = [
    {
      title: 'Vegetable Biryani',
      ingredients: [
        '2 cups basmati rice, soaked',
        '1 cup mixed vegetables (carrots, peas, potatoes, beans), chopped',
        '2 large onions, sliced',
        '2 tomatoes, chopped',
        '1/2 cup yogurt',
        '1 tbsp ginger-garlic paste',
        '2 green chilies, slit',
        '1/4 cup coriander leaves, chopped',
        '1/4 cup mint leaves, chopped',
        '1 tsp cumin seeds',
        '1 tsp turmeric powder',
        '1 tsp red chili powder',
        '1 tsp garam masala',
        'Whole spices (bay leaves, cloves, cardamoms, cinnamon)',
        '4 tbsp ghee/oil',
        'Pinch of saffron in 2 tbsp warm milk',
        'Salt to taste',
        'Fried onions for garnish',
      ],
      instructions: [
        'Cook Rice: Boil water with whole spices and salt. Add rice, cook until 70-80% done, drain.',
        'Prepare Vegetables: Sauté cumin seeds, onions, ginger-garlic paste, and chilies in ghee/oil. Add tomatoes, turmeric, chili powder, and salt. Add vegetables and cook. Mix in yogurt, garam masala, coriander, and mint.',
        'Layer and Cook: Layer half the rice, vegetable mixture, then remaining rice in a pot. Top with saffron milk. Cover and cook on low heat for 20-25 minutes.',
        'Serve: Garnish with fried onions.',
      ],
      time: '50 minutes',
    },
    {
      title: 'Paneer Biryani',
      ingredients: [
        '2 cups basmati rice, soaked',
        '250g paneer, cubed',
        '2 large onions, sliced',
        '2 tomatoes, chopped',
        '1/2 cup yogurt',
        '1 tbsp ginger-garlic paste',
        '2 green chilies, slit',
        '1/4 cup coriander leaves, chopped',
        '1/4 cup mint leaves, chopped',
        '1 tsp cumin seeds',
        '1 tsp turmeric powder',
        '1 tsp red chili powder',
        '1 tsp garam masala',
        'Whole spices (bay leaves, cloves, cardamoms, cinnamon)',
        '4 tbsp ghee/oil',
        'Pinch of saffron in 2 tbsp warm milk',
        'Salt to taste',
        'Fried onions for garnish',
      ],
      instructions: [
        'Cook Rice: Boil water with whole spices and salt. Add rice, cook until 70-80% done, drain.',
        'Prepare Paneer: Sauté cumin seeds, onions, ginger-garlic paste, and chilies in ghee/oil. Add tomatoes, turmeric, chili powder, and salt. Add paneer and cook. Mix in yogurt, garam masala, coriander, and mint.',
        'Layer and Cook: Layer half the rice, paneer mixture, then remaining rice in a pot. Top with saffron milk. Cover and cook on low heat for 20-25 minutes.',
        'Serve: Garnish with fried onions.',
      ],
      time: '55 minutes',
    },
    {
      title: 'Mushroom Biryani',
      ingredients: [
        '2 cups basmati rice, soaked',
        '250g mushrooms, sliced',
        '2 large onions, sliced',
        '2 tomatoes, chopped',
        '1/2 cup yogurt',
        '1 tbsp ginger-garlic paste',
        '2 green chilies, slit',
        '1/4 cup coriander leaves, chopped',
        '1/4 cup mint leaves, chopped',
        '1 tsp cumin seeds',
        '1 tsp turmeric powder',
        '1 tsp red chili powder',
        '1 tsp garam masala',
        'Whole spices (bay leaves, cloves, cardamoms, cinnamon)',
        '4 tbsp ghee/oil',
        'Pinch of saffron in 2 tbsp warm milk',
        'Salt to taste',
        'Fried onions for garnish',
      ],
      instructions: [
        'Cook Rice: Boil water with whole spices and salt. Add rice, cook until 70-80% done, drain.',
        'Prepare Mushrooms: Sauté cumin seeds, onions, ginger-garlic paste, and chilies in ghee/oil. Add tomatoes, turmeric, chili powder, and salt. Add mushrooms and cook. Mix in yogurt, garam masala, coriander, and mint.',
        'Layer and Cook: Layer half the rice, mushroom mixture, then remaining rice in a pot. Top with saffron milk. Cover and cook on low heat for 20-25 minutes.',
        'Serve: Garnish with fried onions.',
      ],
      time: '50 minutes',
    },
    {
      title: 'Jeera Rice',
      ingredients: [
        'Basmati rice: 1 cup',
        'Cumin seeds (jeera): 2 tsp',
        'Bay leaf: 1',
        'Cloves: 2-3',
        'Cardamom pods: 2',
        'Cinnamon stick: 1 inch',
        'Ghee or oil: 2 tbsp',
        'Water: 2 cups',
        'Salt: to taste',
      ],
      instructions: [
        'Rinse basmati rice thoroughly and soak in water for 30 minutes. Drain.',
        'Heat ghee or oil in a pot. Add cumin seeds, bay leaf, cloves, cardamom, and cinnamon stick. Sauté until fragrant.',
        'Add soaked rice and sauté for 2-3 minutes, ensuring the rice is coated with the ghee or oil.',
        'Add water and salt. Bring to a boil, then reduce the heat to low, cover, and cook for 15-20 minutes until the rice is tender and water is absorbed.',
        'Fluff the rice with a fork before serving.',
        'Serve hot with curry or dal.',
      ],
      time: '50 minutes',
    },
    {
      title: 'Veg Fried Rice',
      ingredients: [
        'Cooked rice: 2 cups (preferably a day old)',
        'Mixed vegetables (carrots, beans, peas, capsicum), finely chopped: 1 cup',
        'Onion, finely chopped: 1',
        'Spring onions, chopped: 1/2 cup',
        'Garlic, finely chopped: 2 cloves',
        'Soy sauce: 1 tbsp',
        'Vinegar: 1 tsp',
        'Black pepper powder: 1/2 tsp',
        'Salt: to taste',
        'Oil: 2 tbsp',
      ],
      instructions: [
        'Heat oil in a large pan or wok. Add finely chopped garlic and sauté until fragrant.',
        'Add onions and sauté until they turn translucent.',
        'Add mixed vegetables and stir-fry on high heat for 4-5 minutes until they are cooked but still crisp.',
        'Add cooked rice and mix well. Stir-fry for 2-3 minutes.',
        'Add soy sauce, vinegar, black pepper powder, and salt. Toss well to combine all ingredients.',
        'Garnish with chopped spring onions.',
        'Serve hot as a main dish or side.',
      ],
      time: '50 minutes',
    },
    {
      title: 'Andhra Pulao',
      ingredients: [
        'Basmati rice: 1 cup',
        'Mixed vegetables (carrots, beans, peas, potatoes), chopped: 1 cup',
        'Onion, finely sliced: 1',
        'Tomato, chopped: 1',
        'Green chilies: 2',
        'Ginger-garlic paste: 1 tsp',
        'Bay leaf: 1',
        'Cloves: 2-3',
        'Cardamom pods: 2',
        'Cinnamon stick: 1 inch',
        'Curry leaves: a few',
        'Turmeric powder: 1/2 tsp',
        'Red chili powder: 1 tsp',
        'Garam masala: 1 tsp',
        'Fresh coriander, chopped: for garnish',
        'Fresh mint leaves, chopped: 2 tbsp',
        'Ghee or oil: 2 tbsp',
        'Water: 2 cups',
        'Salt: to taste',
      ],
      instructions: [
        'Rinse basmati rice thoroughly and soak in water for 30 minutes. Drain.',
        'Heat ghee or oil in a pot. Add bay leaf, cloves, cardamom, cinnamon stick, and curry leaves. Sauté until fragrant.',
        'Add finely sliced onions and sauté until golden brown.',
        'Add ginger-garlic paste and green chilies, sauté for a minute.',
        'Add chopped tomatoes, turmeric powder, red chili powder, and salt. Cook until tomatoes turn soft.',
        'Add mixed vegetables and sauté for 2-3 minutes.',
        'Add soaked rice and mix well. Add water and bring to a boil.',
      ],
      time: '50 minutes',
    },
  ];
  