export const muttonRecipes = [
    {
        "title": "Mutton Curry",
        "ingredients": [
          "500g mutton, cut into pieces",
          "2 large onions, finely chopped",
          "2 tomatoes, finely chopped",
          "4 cloves garlic, minced",
          "1 tbsp ginger, minced",
          "3 tbsp vegetable oil",
          "2 bay leaves",
          "1-inch cinnamon stick",
          "4 green cardamom pods",
          "4 cloves",
          "1 tsp cumin seeds",
          "2 tsp ground coriander",
          "1 tsp ground cumin",
          "1 tsp ground turmeric",
          "2 tsp red chili powder",
          "1 tsp garam masala",
          "1 cup plain yogurt",
          "1 cup water",
          "Salt to taste",
          "Fresh cilantro for garnish"
        ],
        "instructions": [
          "Marinate the Mutton:",
          "In a large bowl, mix yogurt with half the garlic, ginger, ground coriander, ground cumin, turmeric, and salt.",
          "Add mutton pieces, mix well, and marinate for at least 2 hours or overnight in the refrigerator.",
          
          "Cook the Mutton:",
          "Heat oil in a large pot or pressure cooker over medium heat.",
          "Add cumin seeds, bay leaves, cinnamon stick, cardamom pods, and cloves. Sauté for a minute until fragrant.",
          "Add the chopped onions and cook until golden brown.",
          "Add the remaining garlic and ginger, and sauté for another minute.",
          
          "Make the Curry Base:",
          "Add the chopped tomatoes and cook until they are soft and the oil starts to separate from the mixture.",
          "Add red chili powder and salt to taste, and cook for another 2 minutes.",
          
          "Combine and Cook:",
          "Add the marinated mutton to the pot and mix well with the tomato-onion mixture.",
          "Cook for about 10 minutes, stirring occasionally, until the mutton is browned and well-coated with the spices.",
          "Add water, stir well, and bring to a boil.",
          
          "Simmer or Pressure Cook:",
          "If using a pot, reduce the heat to low, cover, and simmer for about 1.5 to 2 hours, stirring occasionally, until the mutton is tender.",
          "If using a pressure cooker, cover and cook for about 20-25 minutes after the first whistle. Let the pressure release naturally.",
          
          "Finish the Curry:",
          "Once the mutton is tender, add garam masala and stir well.",
          "Cook for another 5 minutes to let the flavors meld together.",
          
          "Serve:",
          "Garnish with fresh cilantro.",
          "Serve hot with steamed rice, naan, or roti."
        ],
        "time": "2 hours" 
      },
      {
        "title": "Mutton Haleem",
        "ingredients": [
          "500g boneless mutton, cut into small pieces",
          "1 cup cracked wheat (dalia)",
          "1/4 cup chana dal (split chickpeas)",
          "1/4 cup moong dal (split yellow lentils)",
          "1/4 cup masoor dal (split red lentils)",
          "1/4 cup urad dal (split black lentils)",
          "2 large onions, thinly sliced",
          "2 tomatoes, chopped",
          "2 tbsp ginger-garlic paste",
          "4 green chilies, slit",
          "1/2 cup plain yogurt",
          "1 tsp turmeric powder",
          "2 tsp red chili powder",
          "1 tsp garam masala",
          "1 tsp ground coriander",
          "1 tsp ground cumin",
          "4 tbsp ghee or oil",
          "1-inch cinnamon stick",
          "4 green cardamom pods",
          "4 cloves",
          "1 bay leaf",
          "Salt to taste",
          "8 cups water",
          "Fresh cilantro, chopped (for garnish)",
          "Fried onions (for garnish)",
          "Lemon wedges (for serving)"
        ],
        "instructions": [
          "Prepare the Ingredients:",
          "Wash and soak the cracked wheat and all lentils in water for at least 2 hours. Drain and set aside.",
          "Cook the Mutton:",
          "Heat ghee or oil in a large pot over medium heat.",
          "Add cinnamon stick, cardamom pods, cloves, and bay leaf. Sauté until fragrant.",
          "Add the sliced onions and sauté until golden brown.",
          "Add ginger-garlic paste and green chilies, and sauté for another minute.",
          "Add the mutton pieces and cook until they change color.",
          "Add chopped tomatoes, turmeric powder, red chili powder, ground coriander, ground cumin, and salt. Cook until the tomatoes turn soft.",
          "Add yogurt and mix well. Cook for another 5 minutes.",
          "Cook the Wheat and Lentils:",
          "In a separate large pot, add the soaked cracked wheat and lentils with 8 cups of water. Bring to a boil, then reduce the heat and simmer until the wheat and lentils are soft and mushy. This may take about 1-1.5 hours.",
          "Combine Mutton and Wheat Mixture:",
          "Once the wheat and lentils are cooked, add the mutton mixture to the pot. Mix well.",
          "Using a hand blender or a potato masher, blend the mixture to achieve a thick, smooth consistency. Continue cooking on low heat, stirring frequently to prevent sticking.",
          "Finish the Haleem:",
          "Add garam masala and adjust salt to taste. Cook for another 15-20 minutes until the flavors are well blended.",
          "Serve:",
          "Garnish with fresh cilantro and fried onions.",
          "Serve hot with lemon wedges on the side."
        ],
        "time": "Prep time: 30 minutes, Cook time: 3-4 hours"
      },
      {
        "title": "Mutton Ghee Roast",
        "ingredients": [
          "500g mutton, cut into pieces",
          "1/4 cup ghee (clarified butter)",
          "2 large onions, finely sliced",
          "2 tomatoes, finely chopped",
          "1 tbsp ginger-garlic paste",
          "2 tbsp yogurt",
          "1 tsp turmeric powder",
          "1 tsp red chili powder",
          "1 tsp garam masala",
          "Salt to taste",
          "Fresh coriander, chopped (for garnish)",
          "Juice of 1 lemon"
        ],
        "spice_paste": [
          "10 dried red chilies",
          "1 tbsp coriander seeds",
          "1 tsp cumin seeds",
          "1 tsp fennel seeds",
          "1 tsp black peppercorns",
          "1/2 tsp fenugreek seeds",
          "5-6 cloves garlic",
          "1-inch piece of ginger",
          "1/4 cup water"
        ],
        "instructions": [
          "Prepare the Spice Paste:",
          "Dry roast the dried red chilies, coriander seeds, cumin seeds, fennel seeds, black peppercorns, and fenugreek seeds in a pan over medium heat until fragrant. Allow them to cool.",
          "Blend the roasted spices with garlic, ginger, and water to form a smooth paste. Set aside.",
          "Marinate the Mutton:",
          "In a large bowl, mix the mutton pieces with yogurt, turmeric powder, red chili powder, and salt. Marinate for at least 2 hours or overnight in the refrigerator.",
          "Cook the Mutton:",
          "Heat ghee in a large pan over medium heat.",
          "Add the finely sliced onions and sauté until golden brown.",
          "Add ginger-garlic paste and sauté for another minute.",
          "Add the chopped tomatoes and cook until they turn soft and the oil starts to separate from the mixture.",
          "Add the prepared spice paste and cook for 5-7 minutes until the raw smell disappears and the mixture turns aromatic.",
          "Add the marinated mutton pieces and mix well to coat them with the spice mixture.",
          "Cover and cook on low heat for about 45 minutes to 1 hour, stirring occasionally, until the mutton is tender and cooked through. If needed, add a little water to prevent sticking.",
          "Finish the Dish:",
          "Once the mutton is cooked, increase the heat and cook until the ghee starts to separate from the masala and the mixture becomes dry.",
          "Add garam masala and adjust salt to taste. Cook for another 5 minutes.",
          "Serve:",
          "Garnish with fresh coriander and a squeeze of lemon juice.",
          "Serve hot with rice, naan, or roti."
        ],
        "time": "Prep time: 30 minutes, Cook time: 1.5-2 hours"
      },
      {
        "title": "Mutton Manchurian",
        "ingredients": [
          "500g boneless mutton, cut into small pieces",
          "1/4 cup all-purpose flour",
          "1/4 cup cornflour",
          "1 tbsp ginger-garlic paste",
          "1 tbsp soy sauce",
          "1 tbsp red chili sauce",
          "1 tbsp tomato ketchup",
          "1/2 tsp black pepper powder",
          "1/2 tsp salt, or to taste",
          "1 egg, beaten",
          "2 tbsp vegetable oil, for frying",
          "2-3 spring onions, chopped (separate green and white parts)",
          "1 green bell pepper, chopped",
          "1 onion, finely chopped",
          "2-3 garlic cloves, minced",
          "1-inch piece of ginger, minced",
          "1 cup water or broth",
          "1 tbsp cornflour mixed with 2 tbsp water (slurry)",
          "Salt and pepper to taste",
          "Fresh coriander leaves for garnish"
        ],
        "instructions": [
          "Marinate the Mutton:",
          "In a bowl, combine mutton pieces with all-purpose flour, cornflour, ginger-garlic paste, soy sauce, red chili sauce, tomato ketchup, black pepper powder, and salt. Mix well and let it marinate for 30 minutes.",
          "Fry the Mutton:",
          "Heat vegetable oil in a pan over medium-high heat.",
          "Dip each marinated mutton piece in beaten egg and fry in batches until golden brown and crispy. Remove and drain on paper towels.",
          "Prepare the Sauce:",
          "In the same pan, heat 1 tbsp of vegetable oil. Add minced garlic, ginger, and white parts of spring onions. Saute for a minute.",
          "Add chopped onions and bell peppers. Stir-fry for another 2-3 minutes until they are slightly tender.",
          "Add water or broth, soy sauce, red chili sauce, and salt and pepper to taste. Bring to a simmer.",
          "Thicken the Sauce:",
          "Stir in the cornflour slurry and cook until the sauce thickens to your desired consistency.",
          "Finish the Dish:",
          "Add the fried mutton pieces to the sauce. Toss well to coat evenly with the sauce.",
          "Garnish with chopped green onions and fresh coriander leaves.",
          "Serve hot as a appetizer or with steamed rice.",
          "Enjoy your delicious Mutton Manchurian!"
        ],
        "time": "Prep time: 30 minutes, Cook time: 30 minutes"
      },
      {
        "title": "Punjabi Mutton Curry",
        "ingredients": [
          "500g mutton, bone-in pieces",
          "2 onions, finely chopped",
          "2 tomatoes, finely chopped",
          "1/4 cup yogurt",
          "2 tbsp ginger-garlic paste",
          "1 tsp cumin seeds",
          "2 bay leaves",
          "2-3 green cardamom pods",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1 tsp turmeric powder",
          "1 tbsp red chili powder (adjust to taste)",
          "2 tsp coriander powder",
          "1 tsp garam masala powder",
          "Salt to taste",
          "2 tbsp vegetable oil or ghee",
          "Fresh cilantro leaves for garnish"
        ],
        "instructions": [
          "Marinate the Mutton:",
          "In a bowl, mix mutton pieces with yogurt, ginger-garlic paste, turmeric powder, red chili powder, coriander powder, garam masala powder, and salt. Let it marinate for at least 1 hour.",
          "Cook the Curry:",
          "Heat vegetable oil or ghee in a pressure cooker or heavy-bottomed pot over medium heat.",
          "Add cumin seeds, bay leaves, green cardamom pods, cinnamon stick, and cloves. Saute until fragrant.",
          "Add chopped onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften and oil starts to separate from the masala.",
          "Add marinated mutton pieces to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally, until the mutton pieces are lightly browned.",
          "Pressure Cook (if using pressure cooker):",
          "Add 1 cup of water, close the lid, and pressure cook for about 15-20 minutes or until the mutton is tender. Adjust the cooking time according to the tenderness of the mutton and your pressure cooker instructions.",
          "Simmer (if using pot):",
          "If using a pot, add 2 cups of water, bring to a boil, then reduce heat to low. Cover and simmer for 1.5 to 2 hours or until the mutton is tender, stirring occasionally and adding more water if needed.",
          "Finish and Serve:",
          "Once the mutton is cooked and tender, adjust salt and sprinkle garam masala powder.",
          "Garnish with fresh cilantro leaves.",
          "Serve hot with rice, naan, or roti.",
          "Enjoy your flavorful Punjabi Mutton Curry!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 1 hour 30 minutes (may vary)"
      },
      {
        "title": "Mughlai Karahi Gosht",
        "ingredients": [
          "500g mutton, bone-in pieces",
          "2 onions, finely sliced",
          "2 tomatoes, finely chopped",
          "1/2 cup yogurt",
          "2 tbsp ginger-garlic paste",
          "1 tsp cumin seeds",
          "2 bay leaves",
          "4-5 green cardamom pods",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1/2 tsp turmeric powder",
          "1 tbsp red chili powder (adjust to taste)",
          "1 tsp ground coriander",
          "1/2 tsp garam masala powder",
          "Salt to taste",
          "1/4 cup cashew nut paste (optional)",
          "1/4 cup fresh cream",
          "2 tbsp ghee or vegetable oil",
          "Fresh cilantro leaves for garnish"
        ],
        "instructions": [
          "Marinate the Mutton:",
          "In a bowl, mix mutton pieces with yogurt, ginger-garlic paste, turmeric powder, red chili powder, ground coriander, garam masala powder, and salt. Let it marinate for at least 1 hour.",
          "Cook the Mutton:",
          "Heat ghee or oil in a heavy-bottomed pot or karahi over medium heat.",
          "Add cumin seeds, bay leaves, green cardamom pods, cinnamon stick, and cloves. Saute until fragrant.",
          "Add sliced onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften and oil starts to separate from the masala.",
          "Add marinated mutton pieces to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally, until the mutton pieces are lightly browned.",
          "Add cashew nut paste (if using) and mix well.",
          "Pressure Cook (if using pressure cooker):",
          "Add 1 cup of water, close the lid, and pressure cook for about 15-20 minutes or until the mutton is tender. Adjust the cooking time according to the tenderness of the mutton and your pressure cooker instructions.",
          "Simmer (if using pot):",
          "If using a pot, add 1-2 cups of water, bring to a boil, then reduce heat to low. Cover and simmer for 1.5 to 2 hours or until the mutton is tender, stirring occasionally and adding more water if needed.",
          "Finish the Dish:",
          "Once the mutton is cooked and tender, add fresh cream and stir well.",
          "Adjust salt and sprinkle garam masala powder.",
          "Garnish with fresh cilantro leaves.",
          "Serve hot with naan or rice.",
          "Enjoy your delicious Mughlai Karahi Gosht!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 1 hour 30 minutes (may vary)"
      },
      {
        "title": "Pepper Mutton",
        "ingredients": [
          "500g mutton, bone-in pieces",
          "2 onions, finely chopped",
          "2 tomatoes, finely chopped",
          "2 tbsp ginger-garlic paste",
          "1 tbsp black pepper powder (adjust to taste)",
          "1 tsp cumin seeds",
          "2 bay leaves",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1/2 tsp turmeric powder",
          "1 tbsp coriander powder",
          "1/2 tsp garam masala powder",
          "Salt to taste",
          "2 tbsp vegetable oil or ghee",
          "Fresh cilantro leaves for garnish"
        ],
        "instructions": [
          "Marinate the Mutton:",
          "In a bowl, mix mutton pieces with ginger-garlic paste, black pepper powder, turmeric powder, coriander powder, garam masala powder, and salt. Let it marinate for at least 1 hour.",
          "Cook the Mutton:",
          "Heat vegetable oil or ghee in a heavy-bottomed pot over medium heat.",
          "Add cumin seeds, bay leaves, cinnamon stick, and cloves. Saute until fragrant.",
          "Add chopped onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften and oil starts to separate from the masala.",
          "Add marinated mutton pieces to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally, until the mutton pieces are lightly browned.",
          "Pressure Cook (if using pressure cooker):",
          "Add 1 cup of water, close the lid, and pressure cook for about 15-20 minutes or until the mutton is tender. Adjust the cooking time according to the tenderness of the mutton and your pressure cooker instructions.",
          "Simmer (if using pot):",
          "If using a pot, add 1-2 cups of water, bring to a boil, then reduce heat to low. Cover and simmer for 1.5 to 2 hours or until the mutton is tender, stirring occasionally and adding more water if needed.",
          "Finish the Dish:",
          "Once the mutton is cooked and tender, adjust salt and sprinkle additional black pepper powder if desired.",
          "Garnish with fresh cilantro leaves.",
          "Serve hot with rice or naan.",
          "Enjoy your delicious Pepper Mutton!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 1 hour 30 minutes (may vary)"
      },
      {
        "title": "Mutton Chaap",
        "ingredients": [
          "500g mutton chaap (mutton ribs)",
          "2 onions, finely sliced",
          "2 tomatoes, finely chopped",
          "1/2 cup yogurt",
          "2 tbsp ginger-garlic paste",
          "2 tbsp vegetable oil or ghee",
          "1 tsp cumin seeds",
          "2 bay leaves",
          "4-5 green cardamom pods",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1/2 tsp turmeric powder",
          "1 tbsp red chili powder (adjust to taste)",
          "1 tsp ground coriander",
          "1/2 tsp garam masala powder",
          "Salt to taste",
          "Fresh cilantro leaves for garnish"
        ],
        "instructions": [
          "Marinate the Mutton Chaap:",
          "In a bowl, mix mutton chaap with yogurt, ginger-garlic paste, turmeric powder, red chili powder, ground coriander, garam masala powder, and salt. Let it marinate for at least 2 hours or overnight in the refrigerator.",
          "Cook the Mutton Chaap:",
          "Heat vegetable oil or ghee in a heavy-bottomed pot or pressure cooker over medium heat.",
          "Add cumin seeds, bay leaves, green cardamom pods, cinnamon stick, and cloves. Saute until fragrant.",
          "Add sliced onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften and oil starts to separate from the masala.",
          "Add marinated mutton chaap to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally, until the mutton chaap is lightly browned.",
          "Pressure Cook (if using pressure cooker):",
          "Add 1/2 cup of water, close the lid, and pressure cook for about 15-20 minutes or until the mutton chaap is tender. Adjust the cooking time according to the tenderness of the mutton and your pressure cooker instructions.",
          "Simmer (if using pot):",
          "If using a pot, add 1-2 cups of water, bring to a boil, then reduce heat to low. Cover and simmer for 1.5 to 2 hours or until the mutton chaap is tender, stirring occasionally and adding more water if needed.",
          "Finish the Dish:",
          "Once the mutton chaap is cooked and tender, adjust salt if needed.",
          "Garnish with fresh cilantro leaves.",
          "Serve hot with naan or rice.",
          "Enjoy your flavorful Mutton Chaap!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 1 hour 30 minutes (may vary)"
      },
      {
        "title": "Kashmiri Rogan Josh",
        "ingredients": [
          "500g mutton, bone-in pieces",
          "2 onions, finely sliced",
          "2 tomatoes, finely chopped",
          "1/2 cup yogurt",
          "2 tbsp ginger-garlic paste",
          "4 tbsp vegetable oil or ghee",
          "2 bay leaves",
          "4-5 green cardamom pods",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1 tsp cumin seeds",
          "1 tsp fennel seeds",
          "1/2 tsp asafoetida (hing)",
          "2 tsp Kashmiri red chili powder",
          "1 tsp ground coriander",
          "1/2 tsp ground ginger",
          "1/2 tsp ground fennel",
          "1/2 tsp turmeric powder",
          "1/4 tsp ground cinnamon",
          "1/4 tsp ground cloves",
          "1/4 tsp ground cardamom",
          "Salt to taste",
          "Fresh cilantro leaves for garnish"
        ],
        "instructions": [
          "Marinate the Mutton:",
          "In a bowl, mix mutton pieces with yogurt, ginger-garlic paste, Kashmiri red chili powder, ground coriander, ground ginger, ground fennel, turmeric powder, ground cinnamon, ground cloves, ground cardamom, and salt. Let it marinate for at least 2 hours or overnight in the refrigerator.",
          "Cook the Rogan Josh:",
          "Heat vegetable oil or ghee in a heavy-bottomed pot over medium heat.",
          "Add cumin seeds, fennel seeds, bay leaves, green cardamom pods, cinnamon stick, cloves, and asafoetida. Saute until fragrant.",
          "Add sliced onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften and oil starts to separate from the masala.",
          "Add marinated mutton to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally, until the mutton is lightly browned.",
          "Pressure Cook (if using pressure cooker):",
          "Add 1/2 cup of water, close the lid, and pressure cook for about 15-20 minutes or until the mutton is tender. Adjust the cooking time according to the tenderness of the mutton and your pressure cooker instructions.",
          "Simmer (if using pot):",
          "If using a pot, add 1-2 cups of water, bring to a boil, then reduce heat to low. Cover and simmer for 1.5 to 2 hours or until the mutton is tender, stirring occasionally and adding more water if needed.",
          "Finish the Dish:",
          "Once the mutton is cooked and tender, adjust salt if needed.",
          "Garnish with fresh cilantro leaves.",
          "Serve hot with steamed rice or naan.",
          "Enjoy your authentic Kashmiri Rogan Josh!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 1 hour 30 minutes (may vary)"
      },
      {
        "title": "Shahi Mutton Curry",
        "ingredients": [
          "500g mutton, bone-in pieces",
          "2 onions, finely sliced",
          "2 tomatoes, finely chopped",
          "1/2 cup yogurt",
          "1/2 cup cashew nuts, soaked in warm water for 30 minutes",
          "1/4 cup fresh cream",
          "2 tbsp ginger-garlic paste",
          "4 tbsp ghee or vegetable oil",
          "2 bay leaves",
          "4-5 green cardamom pods",
          "1-inch cinnamon stick",
          "4-5 cloves",
          "1 tsp cumin seeds",
          "1 tsp coriander powder",
          "1 tsp garam masala powder",
          "1/2 tsp turmeric powder",
          "1/2 tsp red chili powder (adjust to taste)",
          "1/4 tsp nutmeg powder",
          "Salt to taste",
          "Fresh cilantro leaves for garnish"
        ],
        "instructions": [
          "Marinate the Mutton:",
          "In a bowl, mix mutton pieces with yogurt, ginger-garlic paste, turmeric powder, red chili powder, coriander powder, garam masala powder, nutmeg powder, and salt. Let it marinate for at least 2 hours or overnight in the refrigerator.",
          "Prepare the Cashew Paste:",
          "Blend soaked cashew nuts into a smooth paste using a little water if needed. Set aside.",
          "Cook the Shahi Mutton Curry:",
          "Heat ghee or oil in a heavy-bottomed pot over medium heat.",
          "Add cumin seeds, bay leaves, green cardamom pods, cinnamon stick, and cloves. Saute until fragrant.",
          "Add sliced onions and cook until they turn golden brown.",
          "Add chopped tomatoes and cook until they soften and oil starts to separate from the masala.",
          "Add marinated mutton to the pot. Stir well to coat with the masala.",
          "Cook for 5-7 minutes, stirring occasionally, until the mutton is lightly browned.",
          "Add the cashew nut paste and fresh cream. Stir well to combine.",
          "Cover the pot and cook on low heat for 1.5 to 2 hours or until the mutton is tender, stirring occasionally and adding water if needed to maintain desired consistency.",
          "Finish the Dish:",
          "Once the mutton is cooked and tender, adjust salt if needed.",
          "Garnish with fresh cilantro leaves.",
          "Serve hot with naan or steamed rice.",
          "Enjoy your creamy and flavorful Shahi Mutton Curry!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 1 hour 30 minutes (may vary)"
      },
  ];
  