export const seeFoodRecipes = [

  
    {
        title: 'Fish Curry',
        ingredients: [
          '500g firm white fish fillets, cut into pieces',
          '2 tbsp vegetable oil',
          '1 large onion, finely chopped',
          '2 cloves garlic, minced',
          '1 tbsp ginger, minced',
          '2 green chilies, slit',
          '1 tsp mustard seeds',
          '10 curry leaves',
          '1 tsp ground turmeric',
          '2 tsp ground coriander',
          '1 tsp ground cumin',
          '1 tsp red chili powder',
          '1 cup coconut milk',
          '1 cup water',
          'Juice of 1 lemon',
          'Salt to taste',
          'Fresh cilantro for garnish'
        ],
        instructions: [
          'Heat oil in a large pan over medium heat.',
          'Add mustard seeds and curry leaves, and sauté until they crackle.',
          'Add onions, green chilies, garlic, and ginger, and sauté until onions are golden brown.',
          'Add turmeric, coriander, cumin, and red chili powder, and cook for a minute.',
          'Add coconut milk and water, and bring to a boil.',
          'Add fish pieces and simmer for 10 minutes until fish is cooked through.',
          'Add lemon juice and salt to taste.',
          'Garnish with fresh cilantro and serve hot with steamed rice.'
        ],
        time: 'Prep time: 15 minutes, Cook time: 20-25 minutes',
      },
      {
        title: 'Fish Tacos',
        ingredients: [
          '500g white fish fillets (such as cod or tilapia)',
          '1 tsp ground cumin',
          '1 tsp smoked paprika',
          '1/2 tsp garlic powder',
          '1/2 tsp onion powder',
          '1/2 tsp salt',
          '1/4 tsp black pepper',
          '2 tbsp olive oil',
          'Juice of 1 lime',
          'Corn or flour tortillas',
          '1 cup shredded red cabbage',
          '1/2 cup diced tomatoes',
          '1/2 cup diced red onion',
          '1/4 cup chopped fresh cilantro',
          '1 avocado, sliced',
          'Lime wedges for serving'
        ],
        instructions: [
          'In a small bowl, combine ground cumin, smoked paprika, garlic powder, onion powder, salt, and black pepper.',
          'Sprinkle the spice mixture over both sides of the fish fillets.',
          'Drizzle olive oil and lime juice over the fish, ensuring they are evenly coated.',
          'Let the fish marinate for about 15 minutes.',
          'Heat a large skillet over medium-high heat.',
          'Add the marinated fish fillets to the skillet and cook for about 3-4 minutes per side, until the fish is cooked through and flakes easily with a fork.',
          'Remove the fish from the skillet and let it rest for a few minutes before flaking it into bite-sized pieces.',
          'Warm the tortillas in a dry skillet or microwave.',
          'Place a portion of the flaked fish in each tortilla.',
          'Top with shredded red cabbage, diced tomatoes, diced red onion, chopped cilantro, and avocado slices.',
          'Drizzle the prepared sauce over the top.',
          'Serve the fish tacos with lime wedges on the side for squeezing over the top.'
        ],
        time: 'Prep time: 20 minutes, Cook time: 10 minutes',
      },
      {
        title: 'Garlic Butter Prawns',
        ingredients: [
          '500g large prawns, peeled and deveined',
          '4 tbsp unsalted butter',
          '4 cloves garlic, minced',
          '1 tbsp olive oil',
          'Juice of 1 lemon',
          '1/4 cup fresh parsley, chopped',
          'Salt and pepper to taste',
          'Lemon wedges for serving'
        ],
        instructions: [
          'Pat the prawns dry with paper towels. Season them lightly with salt and pepper.',
          'Heat the olive oil in a large skillet over medium-high heat.',
          'Add the prawns to the skillet and cook for about 2 minutes on each side, until they turn pink and are cooked through.',
          'Remove the prawns from the skillet and set them aside.',
          'In the same skillet, add the butter and let it melt.',
          'Add the minced garlic and sauté for about 1 minute, until fragrant.',
          'Stir in the lemon juice and cook for another 30 seconds.',
          'Return the cooked prawns to the skillet, tossing them to coat in the garlic butter sauce.',
          'Remove the skillet from the heat and sprinkle the chopped parsley over the prawns.',
          'Serve immediately with lemon wedges on the side.'
        ],
        time: 'Prep time: 10 minutes, Cook time: 5-7 minutes',
      },
      {
        "title": "Crab Curry",
        "ingredients": [
          "1 kg crab, cleaned and cut into pieces",
          "2 large onions, finely chopped",
          "2 tomatoes, finely chopped",
          "4 cloves garlic, minced",
          "1 tbsp ginger, minced",
          "3 tbsp vegetable oil",
          "1 tsp mustard seeds",
          "10 curry leaves",
          "2 green chilies, slit",
          "1 tsp turmeric powder",
          "2 tsp red chili powder",
          "1 tbsp coriander powder",
          "1 tsp cumin powder",
          "1 tsp garam masala",
          "1 cup coconut milk",
          "1 cup water",
          "Salt to taste",
          "Fresh coriander for garnish"
        ],
        "instructions": [
          "Prepare the Ingredients:",
          "Clean and cut the crab into pieces. Set aside.",
          "Heat the Oil:",
          "Heat vegetable oil in a large pan over medium heat.",
          "Add the mustard seeds and let them crackle.",
          "Add the curry leaves and green chilies, sauté for a minute.",
          "Cook the Aromatics:",
          "Add the chopped onions and cook until they turn golden brown.",
          "Add the minced garlic and ginger, and sauté for another minute.",
          "Add the Spices:",
          "Add turmeric powder, red chili powder, coriander powder, and cumin powder. Cook for 2 minutes, stirring frequently.",
          "Cook the Tomatoes:",
          "Add the chopped tomatoes and cook until they turn soft and the oil starts to separate from the mixture.",
          "Add the Crab:",
          "Add the cleaned crab pieces to the pan and mix well to coat them with the spice mixture.",
          "Add the Liquids:",
          "Pour in the coconut milk and water, and mix well.",
          "Bring to a Boil:",
          "Bring the mixture to a boil, then reduce the heat to low and let it simmer for about 20-25 minutes, or until the crab is cooked through.",
          "Finish the Curry:",
          "Add garam masala and salt to taste. Mix well and cook for another 5 minutes.",
          "Serve:",
          "Garnish with fresh coriander leaves.",
          "Serve hot with steamed rice or naan."
        ],
        "time": "Prep time: 20 minutes, Cook time: 40 minutes"
      },
      {
        "title": "Crab Fry",
        "ingredients": [
          "1 kg crab, cleaned and cut into pieces",
          "2 large onions, thinly sliced",
          "2 tomatoes, finely chopped",
          "4 cloves garlic, minced",
          "1 tbsp ginger, minced",
          "3 tbsp vegetable oil",
          "1 tsp mustard seeds",
          "10 curry leaves",
          "2 green chilies, slit",
          "1 tsp turmeric powder",
          "2 tsp red chili powder",
          "1 tbsp coriander powder",
          "1 tsp cumin powder",
          "1 tsp garam masala",
          "Salt to taste",
          "Fresh coriander for garnish",
          "Lemon wedges for serving"
        ],
        "instructions": [
          "Prepare the Ingredients:",
          "Clean and cut the crab into pieces. Set aside.",
          "Heat the Oil:",
          "Heat vegetable oil in a large pan over medium heat.",
          "Add the mustard seeds and let them crackle.",
          "Add the curry leaves and green chilies, sauté for a minute.",
          "Cook the Onions:",
          "Add the thinly sliced onions and cook until they turn golden brown.",
          "Add Aromatics:",
          "Add the minced garlic and ginger, and sauté for another minute.",
          "Add the Spices:",
          "Add turmeric powder, red chili powder, coriander powder, and cumin powder. Cook for 2 minutes, stirring frequently.",
          "Cook the Tomatoes:",
          "Add the chopped tomatoes and cook until they turn soft and the oil starts to separate from the mixture.",
          "Add the Crab:",
          "Add the cleaned crab pieces to the pan and mix well to coat them with the spice mixture.",
          "Fry the Crab:",
          "Cook on medium heat, stirring occasionally, until the crab is cooked through and the mixture is dry.",
          "Finish the Dish:",
          "Add garam masala and salt to taste. Mix well and cook for another 2 minutes.",
          "Serve:",
          "Garnish with fresh coriander leaves and lemon wedges.",
          "Serve hot with steamed rice or naan."
        ],
        "time": "Prep time: 20 minutes, Cook time: 30 minutes"
      },
      {
        "title": "Prawns Butter Masala",
        "ingredients": [
          "500g prawns, cleaned and deveined",
          "2 large onions, finely chopped",
          "2 tomatoes, pureed",
          "3 tbsp butter",
          "2 tbsp vegetable oil",
          "1 tbsp ginger-garlic paste",
          "2 green chilies, slit",
          "1 tsp cumin seeds",
          "1/2 tsp turmeric powder",
          "1 tsp red chili powder",
          "1 tsp garam masala",
          "1/2 tsp coriander powder",
          "1/2 cup heavy cream",
          "Salt to taste",
          "Fresh coriander leaves for garnish",
          "Lemon wedges for serving"
        ],
        "instructions": [
          "Prepare the Ingredients:",
          "Clean and devein the prawns. Set aside.",
          "Heat Oil and Butter:",
          "Heat vegetable oil and 2 tbsp of butter in a large pan over medium heat.",
          "Add the cumin seeds and let them crackle.",
          "Add the green chilies and sauté for a minute.",
          "Cook the Onions:",
          "Add the finely chopped onions and cook until they turn golden brown.",
          "Add Aromatics:",
          "Add the ginger-garlic paste and sauté for another minute.",
          "Add the Spices:",
          "Add turmeric powder, red chili powder, and coriander powder. Cook for 2 minutes, stirring frequently.",
          "Cook the Tomatoes:",
          "Add the tomato puree and cook until the oil starts to separate from the mixture.",
          "Add the Prawns:",
          "Add the cleaned prawns to the pan and mix well to coat them with the masala.",
          "Cook the Prawns:",
          "Cook on medium heat, stirring occasionally, until the prawns are cooked through and turn pink.",
          "Finish the Dish:",
          "Add garam masala, salt to taste, and the remaining 1 tbsp of butter. Mix well.",
          "Stir in the heavy cream and cook for another 2 minutes.",
          "Serve:",
          "Garnish with fresh coriander leaves and lemon wedges.",
          "Serve hot with steamed rice or naan."
        ],
        "time": "Prep time: 15 minutes, Cook time: 25 minutes"
      },
      {
        "title": "Prawns 65",
        "ingredients": [
          "500g prawns, cleaned and deveined",
          "1/2 cup yogurt",
          "2 tbsp cornflour",
          "1 tbsp rice flour",
          "1 tbsp ginger-garlic paste",
          "1 tsp red chili powder",
          "1/2 tsp turmeric powder",
          "1 tsp garam masala",
          "Salt to taste",
          "Oil for deep frying",
          "Curry leaves, a handful",
          "2 green chilies, slit",
          "1 tbsp lemon juice",
          "1 onion, thinly sliced (optional, for garnish)",
          "Fresh coriander leaves for garnish"
        ],
        "instructions": [
          "Marinate the Prawns:",
          "In a bowl, mix yogurt, cornflour, rice flour, ginger-garlic paste, red chili powder, turmeric powder, garam masala, and salt.",
          "Add the cleaned prawns to the marinade, mix well, and let it marinate for at least 30 minutes.",
          "Fry the Prawns:",
          "Heat oil in a deep pan over medium-high heat for deep frying.",
          "Once the oil is hot, carefully add the marinated prawns in batches. Fry until they are golden brown and crispy. Remove with a slotted spoon and drain on paper towels.",
          "Prepare the Tempering:",
          "In a separate pan, heat a little oil.",
          "Add curry leaves and slit green chilies. Fry for a minute until fragrant.",
          "Add the fried prawns to the pan and toss well to coat with the tempering.",
          "Finish and Serve:",
          "Sprinkle lemon juice over the prawns and toss once more.",
          "Garnish with thinly sliced onions (optional) and fresh coriander leaves.",
          "Serve hot as a snack or appetizer."
        ],
        "time": "Prep time: 15 minutes, Cook time: 15 minutes"
      },
      {
        "title": "Rajugari Chepala Pulusu",
        "ingredients": [
          "500g fish (like rohu or any firm white fish), cut into pieces",
          "2 large onions, finely chopped",
          "2 tomatoes, finely chopped",
          "3 tbsp vegetable oil",
          "1 tbsp tamarind paste",
          "1 tbsp jaggery or sugar",
          "1/2 tsp turmeric powder",
          "2 tsp red chili powder (adjust to taste)",
          "1 tbsp coriander powder",
          "1/2 tsp fenugreek seeds",
          "1 tsp mustard seeds",
          "10-12 curry leaves",
          "Salt to taste",
          "Fresh coriander leaves for garnish",
          "Lemon wedges for serving"
        ],
        "instructions": [
          "Prepare the Tamarind Water:",
          "Soak the tamarind paste in 1 cup of warm water. Extract the tamarind water and set aside.",
          "Prepare the Fish:",
          "Clean and cut the fish into pieces. Marinate with turmeric powder and a little salt. Set aside.",
          "Cook the Masala:",
          "Heat oil in a pan over medium heat.",
          "Add mustard seeds and fenugreek seeds. Let them splutter.",
          "Add curry leaves and chopped onions. Saute until the onions turn golden brown.",
          "Add ginger-garlic paste and saute for another minute.",
          "Add the chopped tomatoes and cook until they are soft and oil starts to separate from the mixture.",
          "Add Spices:",
          "Add turmeric powder, red chili powder, coriander powder, and salt. Saute for 2 minutes.",
          "Cook the Fish Curry:",
          "Add the marinated fish pieces to the pan. Mix gently to coat with the masala.",
          "Pour in the tamarind water and add jaggery or sugar. Stir well.",
          "Cover and cook on medium heat for about 10-15 minutes, or until the fish is cooked through and the curry thickens.",
          "Finish and Serve:",
          "Garnish with fresh coriander leaves.",
          "Serve hot with steamed rice.",
          "Enjoy your Rajugari Chepala Pulusu!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 30 minutes"
      },
      {
        "title": "Fish Fry",
        "ingredients": [
          "500g fish fillets (such as tilapia or cod)",
          "1/2 cup all-purpose flour",
          "1/4 cup rice flour",
          "1 tbsp red chili powder",
          "1/2 tsp turmeric powder",
          "1 tsp cumin powder",
          "1 tsp coriander powder",
          "1/2 tsp black pepper powder",
          "Salt to taste",
          "Vegetable oil for frying",
          "Lemon wedges for serving"
        ],
        "instructions": [
          "Prepare the Fish:",
          "Clean and pat dry the fish fillets. Cut into pieces if desired. Season with salt and set aside.",
          "Prepare the Coating:",
          "In a shallow bowl, mix all-purpose flour, rice flour, red chili powder, turmeric powder, cumin powder, coriander powder, black pepper powder, and salt.",
          "Coat the Fish:",
          "Dredge each piece of fish in the flour mixture, ensuring it is evenly coated. Shake off any excess flour.",
          "Fry the Fish:",
          "Heat vegetable oil in a frying pan over medium-high heat.",
          "Carefully place the coated fish pieces into the hot oil. Fry in batches to avoid overcrowding.",
          "Fry each side for about 3-4 minutes, or until golden brown and crispy.",
          "Remove the fried fish with a slotted spoon and drain on paper towels to remove excess oil.",
          "Serve:",
          "Serve hot with lemon wedges and your favorite dipping sauce or chutney.",
          "Enjoy your crispy and flavorful Fish Fry!"
        ],
        "time": "Prep time: 15 minutes, Cook time: 15 minutes"
      }
            
];